spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database_platform: org.hibernate.dialect.H2Dialect
    show_sql: true
    hibernate:
      ddl_auto: validate
  flyway:
    enabled: true
    validate-on-migrate: true
